wandb_version: 1

NUM_EPOCHS:
  desc: null
  value: 10
BATCH_SIZE:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722588090
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      - 62
      4: 3.11.4
      5: 0.17.5
      8:
      - 3
      - 5
      13: windows-amd64
