wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: ImageNet
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722584282
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.17.5
      8:
      - 3
      - 5
      13: windows-amd64
